name: Recovery Build

on:
  workflow_dispatch:

env:
  MANIFEST_URL: "https://gitlab.com/OrangeFox/Manifest.git"
  MANIFEST_BRANCH: "12.1"
  DEVICE_TREE_URL: "https://github.com/Yash499-cloud/Il2cppdumper"
  DEVICE_TREE_BRANCH: "main"
  DEVICE_PATH: "device/tecno/TECNO-KI8"
  DEVICE_NAME: "TECNO-KI8"
  MAKEFILE_NAME: "omni_TECNO-KI8"
  BUILD_TARGET: "recovery"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cleanup Space
        uses: rokibhasansagar/slimhub_actions@main

      - name: Set up Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev libncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig

      - name: Install Repo Tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo ln -sf ~/bin/repo /usr/bin/repo

      - name: Sync Source
        run: |
          mkdir ~/work && cd ~/work
          repo init --depth=1 -u ${{ env.MANIFEST_URL }} -b ${{ env.MANIFEST_BRANCH }}
          repo sync -j$(nproc --all) --force-sync --no-tags --no-clone-bundle

      - name: Clone Device Tree
        run: |
          cd ~/work
          git clone ${{ env.DEVICE_TREE_URL }} -b ${{ env.DEVICE_TREE_BRANCH }} ${{ env.DEVICE_PATH }}

      - name: Build
        run: |
          cd ~/work
          export ALLOW_MISSING_DEPENDENCIES=true
          source build/envsetup.sh
          lunch ${{ env.MAKEFILE_NAME }}-eng
          mka ${{ env.BUILD_TARGET }}image -j$(nproc --all)

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: TWRP-Recovery
          path: ~/work/out/target/product/${{ env.DEVICE_NAME }}/recovery.img
          
